cifar100_classes = [
    'apple',
    'aquarium fish',
    'baby',
    'bear',
    'beaver',
    'bed',
    'bee',
    'beetle',
    'bicycle',
    'bottle',
    'bowl',
    'boy',
    'bridge',
    'bus',
    'butterfly',
    'camel',
    'can',
    'castle',
    'caterpillar',
    'cattle',
    'chair',
    'chimpanzee',
    'clock',
    'cloud',
    'cockroach',
    'couch',
    'crab',
    'crocodile',
    'cup',
    'dinosaur',
    'dolphin',
    'elephant',
    'flatfish',
    'forest',
    'fox',
    'girl',
    'hamster',
    'house',
    'kangaroo',
    'keyboard',
    'lamp',
    'lawn mower',
    'leopard',
    'lion',
    'lizard',
    'lobster',
    'man',
    'maple tree',
    'motorcycle',
    'mountain',
    'mouse',
    'mushroom',
    'oak tree',
    'orange',
    'orchid',
    'otter',
    'palm tree',
    'pear',
    'pickup truck',
    'pine tree',
    'plain',
    'plate',
    'poppy',
    'porcupine',
    'possum',
    'rabbit',
    'raccoon',
    'ray',
    'road',
    'rocket',
    'rose',
    'sea',
    'seal',
    'shark',
    'shrew',
    'skunk',
    'skyscraper',
    'snail',
    'snake',
    'spider',
    'squirrel',
    'streetcar',
    'sunflower',
    'sweet pepper',
    'table',
    'tank',
    'telephone',
    'television',
    'tiger',
    'tractor',
    'train',
    'trout',
    'tulip',
    'turtle',
    'wardrobe',
    'whale',
    'willow tree',
    'wolf',
    'woman',
    'worm',
]
flowers  = [
    'pink primrose',
    'hard-leaved pocket orchid',
    'canterbury bells',
    'sweet pea',
    'english marigold',
    'tiger lily',
    'moon orchid',
    'bird of paradise',
    'monkshood',
    'globe thistle',
    'snapdragon',
    "colt's foot",
    'king protea',
    'spear thistle',
    'yellow iris',
    'globe flower',
    'purple coneflower',
    'peruvian lily',
    'balloon flower',
    'giant white arum lily',
    'fire lily',
    'pincushion flower',
    'fritillary',
    'red ginger',
    'grape hyacinth',
    'corn poppy',
    'prince of wales feathers',
    'stemless gentian',
    'artichoke',
    'sweet william',
    'carnation',
    'garden phlox',
    'love in the mist',
    'mexican aster',
    'alpine sea holly',
    'ruby-lipped cattleya',
    'cape flower',
    'great masterwort',
    'siam tulip',
    'lenten rose',
    'barbeton daisy',
    'daffodil',
    'sword lily',
    'poinsettia',
    'bolero deep blue',
    'wallflower',
    'marigold',
    'buttercup',
    'oxeye daisy',
    'common dandelion',
    'petunia',
    'wild pansy',
    'primula',
    'sunflower',
    'pelargonium',
    'bishop of llandaff',
    'gaura',
    'geranium',
    'orange dahlia',
    'pink and yellow dahlia',
    'cautleya spicata',
    'japanese anemone',
    'black-eyed susan',
    'silverbush',
    'californian poppy',
    'osteospermum',
    'spring crocus',
    'bearded iris',
    'windflower',
    'tree poppy',
    'gazania',
    'azalea',
    'water lily',
    'rose',
    'thorn apple',
    'morning glory',
    'passion flower',
    'lotus',
    'toad lily',
    'anthurium',
    'frangipani',
    'clematis',
    'hibiscus',
    'columbine',
    'desert-rose',
    'tree mallow',
    'magnolia',
    'cyclamen',
    'watercress',
    'canna lily',
    'hippeastrum',
    'bee balm',
    'air plant',
    'foxglove',
    'bougainvillea',
    'camellia',
    'mallow',
    'mexican petunia',
    'bromelia',
    'blanket flower',
    'trumpet creeper',
    'blackberry lily',
]

food101 = [
    'apple pie',
    'baby back ribs',
    'baklava',
    'beef carpaccio',
    'beef tartare',
    'beet salad',
    'beignets',
    'bibimbap',
    'bread pudding',
    'breakfast burrito',
    'bruschetta',
    'caesar salad',
    'cannoli',
    'caprese salad',
    'carrot cake',
    'ceviche',
    'cheese plate',
    'cheesecake',
    'chicken curry',
    'chicken quesadilla',
    'chicken wings',
    'chocolate cake',
    'chocolate mousse',
    'churros',
    'clam chowder',
    'club sandwich',
    'crab cakes',
    'creme brulee',
    'croque madame',
    'cup cakes',
    'deviled eggs',
    'donuts',
    'dumplings',
    'edamame',
    'eggs benedict',
    'escargots',
    'falafel',
    'filet mignon',
    'fish and chips',
    'foie gras',
    'french fries',
    'french onion soup',
    'french toast',
    'fried calamari',
    'fried rice',
    'frozen yogurt',
    'garlic bread',
    'gnocchi',
    'greek salad',
    'grilled cheese sandwich',
    'grilled salmon',
    'guacamole',
    'gyoza',
    'hamburger',
    'hot and sour soup',
    'hot dog',
    'huevos rancheros',
    'hummus',
    'ice cream',
    'lasagna',
    'lobster bisque',
    'lobster roll sandwich',
    'macaroni and cheese',
    'macarons',
    'miso soup',
    'mussels',
    'nachos',
    'omelette',
    'onion rings',
    'oysters',
    'pad thai',
    'paella',
    'pancakes',
    'panna cotta',
    'peking duck',
    'pho',
    'pizza',
    'pork chop',
    'poutine',
    'prime rib',
    'pulled pork sandwich',
    'ramen',
    'ravioli',
    'red velvet cake',
    'risotto',
    'samosa',
    'sashimi',
    'scallops',
    'seaweed salad',
    'shrimp and grits',
    'spaghetti bolognese',
    'spaghetti carbonara',
    'spring rolls',
    'steak',
    'strawberry shortcake',
    'sushi',
    'tacos',
    'takoyaki',
    'tiramisu',
    'tuna tartare',
    'waffles',
]

SVHN_classes = [
    'zero',
    'one',
     'two',
    'three',
    'four',
    'five',
    'six',
    'seven',
    'eight',
    'nine',
]


Euro_classes = [
 'Industrial Buildings',
  'Residential Buildings',
  'Annual Crop',
  'Permanent Crop ',
  'River',
   'Sea & Lake', 
   'Herbaceous Vegetation',
    'Highway',
    'Pasture', 
    'Forest'


]




imagenet100_class = [
"chambered nautilus, pearly nautilus, nautilus",
"harvestman, daddy longlegs, Phalangium opilio",
"macaw",
"bittern",
"electric ray, crampfish, numbfish, torpedo",
"drake",
"agama",
"night snake, Hypsiglena torquata",
"indigo bunting, indigo finch, indigo bird, Passerina cyanea",
"tiger shark, Galeocerdo cuvieri",
"flamingo",
"garter snake, grass snake",
"common newt, Triturus vulgaris",
"tench, Tinca tinca",
"sulphur-crested cockatoo, Kakatoe galerita, Cacatua galerita",
"white stork, Ciconia ciconia",
"terrapin",
"diamondback, diamondback rattlesnake, Crotalus adamanteus",
"flatworm, platyhelminth",
"sea snake",
"spiny lobster, langouste, rock lobster, crawfish, crayfish, sea crawfish",
"green snake, grass snake",
"bald eagle, American eagle, Haliaeetus leucocephalus",
"kite",
"goldfish, Carassius auratus",
"scorpion",
"goose",
"bulbul",
"chickadee",
"sea anemone, anemone",
"magpie",
"mud turtle",
"crayfish, crawfish, crawdad, crawdaddy",
"lorikeet",
"garden spider, Aranea diademata",
"spoonbill",
"hermit crab",
"great white shark, white shark, man-eater, man-eating shark, Carcharodon carcharias",
"green mamba",
"bee eater",
"bustard",
"Komodo dragon, Komodo lizard, dragon lizard, giant lizard, Varanus komodoensis",
"hognose snake, puff adder, sand viper",
"common iguana, iguana, Iguana iguana",
"king snake, kingsnake",
"toucan",
"peacock",
"barn spider, Araneus cavaticus",
"wolf spider, hunting spider",
"thunder snake, worm snake, Carphophis amoenus",
"water ouzel, dipper",
"Dungeness crab, Cancer magister",
"nematode, nematode worm, roundworm",
"vine snake",
"wombat",
"black widow, Latrodectus mactans",
"oystercatcher, oyster catcher",
"black grouse",
"red-backed sandpiper, dunlin, Erolia alpina",
"goldfinch, Carduelis carduelis",
"snail",
"hammerhead, hammerhead shark",
"spotted salamander, Ambystoma maculatum",
"American alligator, Alligator mississipiensis",
"banded gecko",
"wallaby, brush kangaroo",
"great grey owl, great gray owl, Strix nebulosa",
"jellyfish",
"black swan, Cygnus atratus",
"ptarmigan",
"hummingbird",
"whiptail, whiptail lizard",
"sidewinder, horned rattlesnake, Crotalus cerastes",
"hen",
"horned viper, cerastes, sand viper, horned asp, Cerastes cornutus",
"albatross, mollymawk",
"axolotl, mud puppy, Ambystoma mexicanum",
"tailed frog, bell toad, ribbed toad, tailed toad, Ascaphus trui",
"American coot, marsh hen, mud hen, water hen, Fulica americana",
"loggerhead, loggerhead turtle, Caretta caretta",
"redshank, Tringa totanus",
"crane",
"tick",
"sea lion",
"tarantula",
"boa constrictor, Constrictor constrictor",
"conch",
"prairie chicken, prairie grouse, prairie fowl",
"pelican",
"coucal",
"limpkin, Aramus pictus",
"chiton, coat-of-mail shell, sea cradle, polyplacophore",
"black and gold garden spider, Argiope aurantia",
"leatherback turtle, leatherback, leathery turtle, Dermochelys coriacea",
"stingray",
"rock crab, Cancer irroratus",
"green lizard, Lacerta viridis",
"sea slug, nudibranch",
"hornbill",
"cock",
]





iwildcam_class = ['empty',
 'tayassu pecari',
 'dasyprocta punctata',
 'cuniculus paca',
 'puma concolor',
 'tapirus terrestris',
 'pecari tajacu',
 'mazama americana',
 'leopardus pardalis',
 'geotrygon montana',
 'nasua nasua',
 'dasypus novemcinctus',
 'eira barbara',
 'didelphis marsupialis',
 'procyon cancrivorus',
 'panthera onca',
 'myrmecophaga tridactyla',
 'tinamus major',
 'sylvilagus brasiliensis',
 'puma yagouaroundi',
 'leopardus wiedii',
 'mazama gouazoubira',
 'philander opossum',
 'capra aegagrus',
 'bos taurus',
 'ovis aries',
 'canis lupus',
 'lepus saxatilis',
 'papio anubis',
 'genetta genetta',
 'tragelaphus scriptus',
 'herpestes sanguineus',
 'loxodonta africana',
 'cricetomys gambianus',
 'raphicerus campestris',
 'hyaena hyaena',
 'aepyceros melampus',
 'crocuta crocuta',
 'caracal caracal',
 'equus ferus',
 'panthera leo',
 'tragelaphus oryx',
 'kobus ellipsiprymnus',
 'phacochoerus africanus',
 'panthera pardus',
 'ichneumia albicauda',
 'canis mesomelas',
 'syncerus caffer',
 'equus quagga',
 'giraffa camelopardalis',
 'alcelaphus buselaphus',
 'chlorocebus pygerythrus',
 'madoqua guentheri',
 'potamochoerus larvatus',
 'nanger granti',
 'eudorcas thomsonii',
 'struthio camelus',
 'orycteropus afer',
 'acinonyx jubatus',
 'eupodotis senegalensis',
 'felis silvestris',
 'oryx beisa',
 'lophotis gindiana',
 'ardeotis kori',
 'lissotis melanogaster',
 'argusianus argus',
 'prionailurus bengalensis',
 'hemigalus derbyanus',
 'muntiacus muntjak',
 'sus scrofa',
 'helarctos malayanus',
 'rusa unicolor',
 'hystrix brachyura',
 'pardofelis temminckii',
 'panthera tigris',
 'lariscus insignis',
 'chalcophaps indica',
 'genetta tigrina',
 'hystrix cristata',
 'lycaon pictus',
 'procavia capensis',
 'canis familiaris',
 'unknown bird',
 'unknown bat',
 'momotus momota',
 'dasyprocta fuliginosa',
 'geotrygon sp',
 'nasua narica',
 'tamandua mexicana',
 'didelphis sp',
 'penelope purpurascens',
 'phaetornis sp',
 'brotogeris sp',
 'camelus dromedarius',
 'otocyon megalotis',
 'acryllium vulturinum',
 'equus grevyi',
 'proteles cristata',
 'leptailurus serval',
 'tragelaphus strepsiceros',
 'hippopotamus amphibius',
 'burhinus capensis',
 'paguma larvata',
 'pardofelis marmorata',
 'cuon alpinus',
 'varanus salvator',
 'martes flavigula',
 'prionodon linsang',
 'rollulus rouloul',
 'lophura inornata',
 'polyplectron chalcurum',
 'manis javanica',
 'capricornis sumatraensis',
 'macaca sp',
 'francolinus nobilis',
 'cercopithecus lhoesti',
 'cephalophus nigrifrons',
 'atherurus africanus',
 'pan troglodytes',
 'cercopithecus mitis',
 'funisciurus carruthersi',
 'motacilla flava',
 'andropadus latirostris',
 'andropadus virens',
 'thamnomys venustus',
 'protoxerus stangeri',
 'paraxerus boehmi',
 'cephalophus silvicultor',
 'oenomys hypoxanthus',
 'melocichla mentalis',
 'hybomys univittatus',
 'colomys goslingi',
 'hylomyscus stella',
 'genetta servalina',
 'canis adustus',
 'mus minutoides',
 'musophaga rossae',
 'turtur tympanistria',
 'praomys tullbergi',
 'malacomys longipes',
 'alopochen aegyptiaca',
 'deomys ferrugineus',
 'francolinus africanus',
 'turdus olivaceus',
 'mazama sp',
 'urocyon cinereoargenteus',
 'meleagris ocellata',
 'crax rubra',
 'agouti paca',
 'tapirus bairdii',
 'procyon lotor',
 'odocoileus virginianus',
 'leptotila plumbeiceps',
 'mazama temama',
 'conepatus semistriatus',
 'mazama pandora',
 'ortalis vetula',
 'presbytis thomasi',
 'neofelis diardi',
 'arctonyx hoevenii',
 'tragulus sp',
 'dendrocitta occipitalis',
 'niltava sumatrana',
 'leiothrix argentauris',
 'arborophila rubrirostris',
 'lophura sp',
 'myiophoneus glaucinus',
 'lophura erythrophthalma',
 'spilornis cheela',
 'myiophoneus caeruleus',
 'herpestes semitorquatus',
 'cerdocyon thous',
 'motorcycle',
 'peromyscus sp',
 'puma yagoroundi',
 'tigrisoma mexicanum',
 'claravis pretiosa',
 'sciurus sp',
 'ave desconocida',
 'aramides cajanea',
 'unknown dove',
 'mazama  temama',
 'myiophoneus melanurus',
 'turtur calcospilos',
 'equus africanus',
 'helogale parvula',
 'streptopilia senegalensis',
 'ictonyx striatus',
 'canis latrans',
 'psophia crepitans',
 'nothocrax urumutum',
 'myoprocta pratti',
 'proechimys sp',
 'aguila sp',
 'callosciurus notatus',
 'collocalia linchi',
 'aramus guarauna',
 'xerus rutilus',
 'dioptrornis fischeri',
 'eurocephalus rueppelli',
 'nandinia binotata',
 'mesopicos griseocephalus',
 'erithacus cyane',
 'streptopelia lugens',
 'mustela lutreolina',
 'paleosuchus sp']


Camelyon_class = ['containing', 
 'not containing']


FMoW_class = ["airport", 
"airport_hangar", 
"airport_terminal",
"amusement_park",
"aquaculture", 
"archaeological_site",
"barn", 
"border_checkpoint", 
"burial_site",
"car_dealership",
"construction_site",
"crop_field",
"dam",
"debris_or_rubble",
"educational_institution", 
"electric_substation",
"factory_or_powerplant",
"fire_station",
"flooded_road", 
"fountain", 
"gas_station",
"golf_course", 
"ground_transportation_station", 
"helipad", 
"hospital", 
"impoverished_settlement", 
"interchange",
"lake_or_pond",
"lighthouse",
"military_facility",
"multi-unit_residential",
"nuclear_powerplant", 
"office_building",
"oil_or_gas_facility", 
"park",
"parking_lot_or_garage",
"place_of_worship",
"police_station",
"port",
"prison",
    "race_track",
    "railway_bridge",
    "recreational_facility", 
    "road_bridge", 
    "runway", 
    "shipyard", 
    "shopping_mall",
    "single-unit_residential", 
    "smokestack", 
    "solar_farm",
        "space_facility",
        "stadium", 
        "storage_tank", 
        "surface_mine", 
        "swimming_pool",
        "toll_booth", 
        "tower",
        "tunnel_opening",
            "waste_disposal",
            "water_treatment_facility",
            "wind_farm", 
            "zoo"]





clevr_class = [
    'three',
    'four',
    'five',
    'six',
    'seven',
    'eight',
    'nine',
    'ten'
]

dmlab_classes = [
('close', 'positive'),
('far', 'positive'),
('very far', 'positive'),
('close', 'negative'),
('far', 'negative'),
('very far', 'negative')
]


dtd_classes =['banded', 'blotchy', 'braided', 'bubbly', 'bumpy', 'chequered', 'cobwebbed', 'cracked', 'crosshatched', 'crystalline', 'dotted', 'fibrous', 'flecked', 'freckled', 'frilly', 'gauzy', 'grid', 'grooved', 'honeycombed', 'interlaced', 'knitted', 'lacelike', 'lined', 'marbled', 'matted', 'meshed', 'paisley', 'perforated', 'pitted', 'pleated', 'polka-dotted', 'porous', 'potholed', 'scaly', 'smeared', 'spiralled', 'sprinkled', 'stained', 'stratified', 'striped', 'studded', 'swirly', 'veined', 'waffled', 'woven', 'wrinkled', 'zigzagged']


resisc_classes = ['airplane', 'airport', 'baseball_diamond', 'basketball_court', 'beach', 'bridge', 'chaparral', 'church', 'circular_farmland', 'cloud', 'commercial_area', 'dense_residential', 'desert', 'forest', 'freeway', 'golf_course', 'ground_track_field', 'harbor', 'industrial_area', 'intersection', 'island', 'lake', 'meadow', 'medium_residential', 'mobile_home_park', 'mountain', 'overpass', 'palace', 'parking_lot', 'railway', 'railway_station', 'rectangular_farmland', 'river', 'roundabout', 'runway', 'sea_ice', 'ship', 'snowberg', 'sparse_residential', 'stadium', 'storage_tank', 'tennis_court', 'terrace', 'thermal_power_station', 'wetland']


caltech_classes = ['accordion', 'airplanes', 'anchor', 'ant', 'background_google', 'barrel', 'bass', 'beaver', 'binocular', 'bonsai', 'brain', 'brontosaurus', 'buddha', 'butterfly', 'camera', 'cannon', 'car_side', 'ceiling_fan', 'cellphone', 'chair', 'chandelier', 'cougar_body', 'cougar_face', 'crab', 'crayfish', 'crocodile', 'crocodile_head', 'cup', 'dalmatian', 'dollar_bill', 'dolphin', 'dragonfly', 'electric_guitar', 'elephant', 'emu', 'euphonium', 'ewer', 'faces', 'faces_easy', 'ferry', 'flamingo', 'flamingo_head', 'garfield', 'gerenuk', 'gramophone', 'grand_piano', 'hawksbill', 'headphone', 'hedgehog', 'helicopter', 'ibis', 'inline_skate', 'joshua_tree', 'kangaroo', 'ketch', 'lamp', 'laptop', 'leopards', 'llama', 'lobster', 'lotus', 'mandolin', 'mayfly', 'menorah', 'metronome', 'minaret', 'motorbikes', 'nautilus', 'octopus', 'okapi', 'pagoda', 'panda', 'pigeon', 'pizza', 'platypus', 'pyramid', 'revolver', 'rhino', 'rooster', 'saxophone', 'schooner', 'scissors', 'scorpion', 'sea_horse', 'snoopy', 'soccer_ball', 'stapler', 'starfish', 'stegosaurus', 'stop_sign', 'strawberry', 'sunflower', 'tick', 'trilobite', 'umbrella', 'watch', 'water_lilly', 'wheelchair', 'wild_cat', 'windsor_chair', 'wrench', 'yin_yang']